### PR TITLE
Dynamic URI depth match

### PR DESCRIPTION
**Pull request by marcnewton**
Allows control over uri slug depth check, useful for side-by-side column navigation where a primary navigation has single depth URI link while viewing a child page of a sub menu.

Request: **/settings/users**

*App.js*
```javascript
    Mavigator.mark('aside.main', {
        depth: 1
    });

    Mavigator.mark('aside.sub');
```

```/settings``` is matched in aside.main

```html
    <aside class="main">
        <nav role="navigation">
            <div class="navbar-header">
                <a role="menuitem" href="/" title="Dashboard"><span class="glyphicons glyphicons-show-thumbnails"></span></a>
            </div>

            <div class="nav navbar-nav admin-nav">
                <a role="menuitem" href="/settings" title="System Settings" class="active"><span class="glyphicons glyphicons-settings"></span></a>
            </div>
        </nav>
    </aside>
```

```/settings/users``` is matched in aside.sub

```html
    <aside class="sub">
        <nav>
            <h6>GENERAL</h6>
            <a href="/settings/users" class="active">Users</a>
            <a href="/settings/access">Access Keys</a>
        </nav>
    </aside>
```

### CODE REVIEW

**Comment by kfirba** [comment]
@marcnewton Hey.

Thanks for the PR. I'm trying to understand how can this feature come handy? Your implementation does not eliminate the need to invoke `Mavigator` twice. Why not just invoke `Mavigator` twice with the correct URI:

```
// Call 1:
Mavigator.mark('aside.main', {uri: '/settings'});

// If you want to make it dynamic, we can use some basic JS methods (Note that the "3" is the [depth+1] since we keep the initial '/'):
Mavigator.mark('aside.main', {
    uri: window.location.pathname.split('/').splice(0, 3).join('/')
});

// Cal 2:
Mavigator.mark('aside.sub');
```

I

**Comment by marcnewton** [comment]
Heya I'll get back to you soon with usage case, why two instances and why
the uri option did not work for me.

**Comment by marcnewton** [comment]
Heya.
So firstly I went with the depth option because the menu items change depending on the current user logged in. It made sense to avoid writing out a list of URi's in javascript since the structure of the menu is unknown beforehand on each page load.

Secondly there is no reason to try and make this script do everything with a single instance, Multiple instances focused on smaller scopes are more optimal and prevent conflict with other scripts running in the document.

Finally the second instance for the second menu is not present on every single page, the sub menu only appears on some pages.

I have added an image you can see the layout: 

links-example

The only thing missing is a callback on ready function in your module, The second instance (aside.stage) was intended to be called only when a Laravel view extended a staged view that contains the sub-menu that in turn extends the main layout housing the main navigation. At the moment in order to fire aside.stage the second instance call has to be in app.php even though the menu is not there all the time.
I am trying to keep it free of statement congestion by avoiding conditional statements that check if elements exist and only fire directly from template when actually needed.
It speeds up development and reduces instruction by dropping the requirement of having to place additional code in JS just for navigation function.

Hope this clears up your query and you find it useful enough to include for others to use. 

Another way of wording it is that I am trying to make the javascript for my application be passive to cut down on additional JS editing, a "Touch it once" policy.

**Comment by kfirba** [comment]
Hey.

I’m still having hard time understanding how your PR makes the process of marking the `/settings` easier or more “predictable”. I’m also not sure why you need to add any call to Mavigator in your `app.php` file. If you share gist with the way your menu is wired up I’m sure we can come up with a clever way to simplify it.

Anyways, I think that your PR is good but if we are going down that route, let’s expand on it a little bit. Instead of making the `depth` mark only links that match the specified depth, what we can do is make it collect more links to mark along with the current `uri` provided to Mavigator.

For example, given your menu structure, if we invoke Mavigator like this:

```js
Mavigator.mark(‘aside’, { markTraversedTreeDepth: 1 });
```

It will look for any link that that is inside an `aside` tag with the url of **/settings/access** and also look for links like **/settings** since it’s 1 level up. On that note, we’ll need to decide whether it looks 1 level up or it starts from the beginning of the tree. For example, the uri **/settings/sub/access** with the depth of **1**, should it also match **/settings** (starting from the “root”) or **/settings/sub** (starting from the bottom of the tree)?

By default, that parameter will be either `false` or `0` and it will only match the current URI which makes this change a non-breaking change. 

By doing that, it completely eliminates the need to invoke Mavigator twice. With a single call we can achieve the same result. 

What do you think?

**Comment by marcnewton** [comment]
I think you do indeed need to add support for that functionality but even if you implemented it in that manner, I still would rather use multiple instances for watching separate scopes for a number of reasons:

Firstly I am working with VUE Framework interfaces in some areas of the application I would not want a 3rd party module using a single instance to watch a lager scope of the document as this could cause function conflicts with DOM elements and other modules.

Secondly the application accounts for various independent sections running other JS tools where conflicts would need to be avoided.

Thirdly the two menus while related are not in an immediate shared navigation scope due to the layout, they are in completely separate element groups from each other so your single scope proposal cant work for it without having the scope on a higher element that incorporates my first two points.

Finally Deep Scoping is much safer in practice as well as more optimal than a global scopes.

There is no point in always trying to make one thing do everything, while it's nice at times and too often the main goal of project developer it can be more destructive than actually beneficial.

Hope this helps.

P.S i found my issue with being confined to app.js, My script load order was wrong.

**Comment by kfirba** [comment]
@marcnewton Hey.

You don't need to let Mavigator watch a big part of the document. The selector option is compatible with the `querySelectorAll()` method so you can easily pass a string like this:

```js
Mavigator.mark('aside.main, aside.sub');
```

There is really zero chance of any conflict here.

I'm working on a new branch that will offer a new option: `markTreeDepth`. By doing that, your two calls can be used like:

```js
Mavigator.mark('aside.main, aside.sub', {
    markTreeDepth: 1
});
```

Given we are on the **/settings/access** page, the call above will look for links only in the `aside.main` and the `aside.sub` elements and will match links with the following URL:

1. /settings/access
2. /settings

The `markTreeDepth` accepts the following options:

1. **0** - Will only mark the current page URI, for a page URI like **/settings/access/sub**, the URI that will be matched is **/settings/access/sub** alone.
2. **-1** - Will match every URI segment. For a URI like **/settings/access/sub**, the URIs that will be matched are:
    * /settings/access/sub
    * /settings/access
    * /settings
3. **1,2,3,...,n** - Will match every URI segment up to the given numeric value. For a URI like **/settings/access/sub** and the value *1*, the URIs that will be matched are:
    * /settings/access/sub
    * /settings/access

As you can deduce from the example above, there really is no need to invoke Mavigator twice. If you really want to, you can really just separate the two calls like so:

```js
Mavigator.mark('aside.main');

Mavigator.mark('aside.sub', {
    markTreeDepth: 1 // Will match /settings/access and /settings only in the 'aside.sub' element.
});
```

I appreciate the fact that you created this PR. In fact, without this PR the feature above would've never been "born". I would love it if you could give me some feedback about the new branch's feature: https://github.com/kfirba/Mavigator/blob/feature/mark-traveresed-tree/src/mavigator.js#L78

**Comment by marcnewton** [comment]
Sounds good, although I am a little but concerned how the single instance will behave if **markTreeDepth** is used when multiple scopes are listed but we shall see in some test cases if any strange behaviour occurs.

Thanks for your time to look into this.

**Comment by kfirba** [comment]
@marcnewton the major change I made is that I now generate a list of all of the URIs that should be marked and then filter through the found links and match them. It means that it will look for those generated list of URIs in both scopes.

I’ve just published a new version, 1.10.0, so you can play with it. Let me know if you find any funny edge case ;)!

**Comment by marcnewton** [comment]
Heya, I have updated to the new version. Appears to be operating as expected, current implementation of single instance is working well with current distant parent > child menu layout it is operating on, I will let you know if there are any url combinations that it can't handle as the project gets bigger.

```js
import Mavigator from 'mavigator';

Mavigator.mark('nav.main,nav.stage', {
	markTreeDepth: 1
});
```

Thanks for the update 👍 

PS I noticed that your project appears twice when browsing Node Packages to install: `mavigator` (1.1.0) and `Mavigator` (1.0.0). It looks like uppercase **M** of this git repo is connected to the lower case **m** found on npmJS/

mavi

**Pull request closed without merging**
